title: <p align="center"> Dr.N.V.Uma Reddy </p>
logo: C:\Users\ADMIN\Desktop\photo.jpg
description: 
<p align="center">

<br>
I am working as a professor in the department of AIML

<br>
</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
